[package]
name = "boozle-actor"
version = "0.1.0"
authors = ["beta <bmcdorman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]


[dependencies]
futures = "0.3.5"